version: "3.8"

services:

  #------------------------------------#
  #------| Streams Pulsar utils |------#
  #------------------------------------#
  data-provider:
    build: ./prototype-data-provider
    environment:
      PRODUCER_URL: producer
      PRODUCER_PORT: 8992
    depends_on:
      - producer

  #-----------------------------------#
  #----| Implementation Services |----#
  #-----------------------------------#
  producer:
    build: ./producer
    environment:
      PULSAR_BROKER_URL: 'pulsar://broker,broker-2'
    ports:
      - 8992:8992

  consumer:
    build: ./consumer
    environment:
      PULSAR_BROKER_URL: 'pulsar://broker-1,broker-2'
    depends_on:
      - broker
    ports:
      - 8993:8992
      
  broker-1:
    image: apachepulsar/pulsar:2.6.0
    ports:
      - 8080:8080
      - 6650:6650
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"    
    command: bin/pulsar standalone

  broker-2:
    image: apachepulsar/pulsar:2.6.0
    ports:
      - 8081:8080
      - 6651:6650
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"    
    command: bin/pulsar standalone