name: Deploy Javadoc

on:
  push:
    branches: [ master, feature/javadoc]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: Klungerbo/javadoc-publisher.yml@b36cbbb27da7ba3fe6ef3b7912168db6109e7ab7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: gh-pages 
          java-version: 17
          target-folder: .
