name: Deploy Javadoc

on:
  push:
    branches: [ master, feature/javadoc]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@916a6e4006cd016e1b1d7b2421c23d68f277c3fe
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: gh-pages 
          java-version: 17
          target-folder: javadoc
